name: Deploy to server

on:
  push:
    branches: [main]

jobs:
  first_job:
    name: Jobs name
    runs-on: ubuntu-latest
    env:
      NAME: VariablePruba
      PORT: 3000
    outputs:
      salida: salida del job
      job_port: "3000"
      stepId: ${{ steps.step_github_output.outputs.currentId }}
    steps:
      - name: Hola mundo
        run: echo "Hola mundo desde $PORT"

      - name: list working dir runner
        run: ls -al

      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: list working dir repo
        run: ls -al

      - name: Github output
        id: step_github_output
        run: echo "currentId=243j342sdt" >> $GITHUB_OUTPUT

      - name: Obtener output
        run: echo " salida del step anterior es - ${{ steps.step_github_output.outputs.currentId }}"

      - name: Generar archivo
        run: |
          echo "Arvhico prueba, hola" >> test.log

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: logs_aplicacion
          path: test.log

  second_job:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: first_job
    runs-on: ubuntu-latest

    steps:
      - name: Hola mundo
        run: echo "Hola mundo desde el segundo"

      - name: Obtener data de otro job
        run: echo "Esto viene del job anterior ${{ needs.first_job.outputs.stepId }} "

      - name: Obtener artefacto de otro job
        uses: actions/download-artifact@v4
        with:
          name: logs_aplicacion

      - name: Display structure of downloaded files
        run: ls -R
