name: Deploy to server

on:
  push:
    branches: [main]

jobs:
  first_job:
    name: Jobs name
    runs-on: ubuntu-latest
    env:
      NAME: VariablePruba
      PORT: 3000
    steps:
      - name: Hola mundo
        run: echo "Hola mundo desde $PORT"

      - name: list working dir runner
        run: ls -al

      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: list working dir repo
        run: ls -al

  second_job:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: first_job
    runs-on: ubuntu-latest

    steps:
      - name: Hola mundo
        run: echo "Hola mundo desde el segundo"
