name: Deploy to server

on:
  push:
    branches: [main]

jobs:
  first_job:
    name: Strategy
    runs-on: ubuntu-latest

    strategy:
      matrix:
        message: ["Hola", "Prueba", "estrategia"]

    steps:
      - name: Print mensaje
        run: echo "${{ matrix.message }}"
